### PR TITLE
Gradle: Revise the gradle build script to support AGP 8.3

### PR DESCRIPTION
**Pull request by wooksong**
This patch revises the gradle build script and adds gradle-wrapper related files to support AGP 8.3.

Signed-off-by: Wook Song <wook16.song@samsung.com>

### CODE REVIEW

**Review by DonghakPark — APPROVED** [review]
LGTM!

**Review by niley7464 — APPROVED** [review]
LGTM 👍 
Thank you~!!

**Comment by niley7464** [comment]
How about remove `ndk.dir` in android_api/local.properties?

Related with : https://github.com/nnstreamer/api/pull/477#pullrequestreview-1964999635

**Review by anyj0527 — APPROVED** [review]
LGTM👍. And #41 would resolve @niley7464 's comment

**Pull request merged**
